// Icon registry — maps string keys to lucide-react components.
// Data files reference icons by name (a plain string) so the data layer
// stays free of component imports; UI components resolve names via getIcon().
import {
  Linkedin,
  Mail,
  Phone,
  MapPin,
  BookOpen,
  Briefcase,
  Code2,
  Menu,
  X,
  Terminal,
  Layout,
  Sparkles,
  Users,
  Rocket,
  GraduationCap,
  MessageCircle,
  ArrowRight,
  CheckCircle2,
  Github,
  Target,
  Wrench,
  TrendingUp,
  Handshake,
  Lightbulb,
  Brain,
  Bot,
  Zap,
  Compass,
  FlaskConical,
  ExternalLink,
  Hand,
} from 'lucide-react';

const icons = {
  linkedin: Linkedin,
  mail: Mail,
  phone: Phone,
  mapPin: MapPin,
  bookOpen: BookOpen,
  briefcase: Briefcase,
  code: Code2,
  menu: Menu,
  close: X,
  terminal: Terminal,
  layout: Layout,
  sparkles: Sparkles,
  users: Users,
  rocket: Rocket,
  graduation: GraduationCap,
  message: MessageCircle,
  arrowRight: ArrowRight,
  check: CheckCircle2,
  github: Github,
  target: Target,
  wrench: Wrench,
  trendingUp: TrendingUp,
  handshake: Handshake,
  lightbulb: Lightbulb,
  brain: Brain,
  bot: Bot,
  zap: Zap,
  compass: Compass,
  flask: FlaskConical,
  externalLink: ExternalLink,
  hand: Hand,
};

// Resolve an icon name to its component. Falls back to a visible default
// so a typo surfaces in the UI instead of crashing the render.
export const getIcon = (name) => icons[name] || Code2;
